"""GitHub PR comment formatter for Fenceline results."""

from __future__ import annotations

from typing import Any, List


def format_pr_comment(results: List[Any]) -> str:
    """Produce a markdown PR comment from check results.

    Args:
        results: List of result dicts with keys: name, change, risk_score,
                 risk_level ("critical", "review", "low"), signals.

    Returns:
        Formatted markdown string for a GitHub PR comment.
    """
    if not results:
        return (
            "## Fenceline Supply Chain Check\n\n"
            "No package changes detected.\n\n"
            "---\n"
            "*Generated by [Fenceline](https://github.com/Karmona/Fenceline) "
            "--- supply chain security, community-driven*"
        )

    # Categorize results
    critical = [r for r in results if r.get("risk_level") == "critical"]
    review = [r for r in results if r.get("risk_level") == "review"]
    low = [r for r in results if r.get("risk_level") == "low"]

    total = len(results)
    lines: List[str] = []

    # Header
    lines.append("## Fenceline Supply Chain Check")
    lines.append("")
    lines.append(
        f"**{total} packages changed** | "
        f"{len(critical)} critical | "
        f"{len(review)} needs review | "
        f"{len(low)} low risk"
    )
    lines.append("")

    # Critical section
    if critical:
        lines.append("### Critical Risk")
        lines.append("")
        lines.append("| Package | Change | Risk | Signals |")
        lines.append("|---------|--------|------|---------|")
        for r in critical:
            signals = ", ".join(r.get("signals", []))
            score = r.get("risk_score", "?")
            lines.append(
                f"| {r['name']} | {r.get('change', '')} | "
                f"CRITICAL ({score}) | {signals} |"
            )
        lines.append("")

    # Needs review section
    if review:
        lines.append("### Needs Review")
        lines.append("")
        lines.append("| Package | Change | Risk | Signals |")
        lines.append("|---------|--------|------|---------|")
        for r in review:
            signals = ", ".join(r.get("signals", []))
            score = r.get("risk_score", "?")
            lines.append(
                f"| {r['name']} | {r.get('change', '')} | "
                f"REVIEW ({score}) | {signals} |"
            )
        lines.append("")

    # Low risk section (collapsed)
    if low:
        lines.append(f"<details><summary>Low Risk ({len(low)} packages)</summary>")
        lines.append("")
        lines.append("| Package | Change | Risk | Signals |")
        lines.append("|---------|--------|------|---------|")
        for r in low:
            signals = ", ".join(r.get("signals", []))
            score = r.get("risk_score", "?")
            lines.append(
                f"| {r['name']} | {r.get('change', '')} | "
                f"LOW ({score}) | {signals} |"
            )
        lines.append("")
        lines.append("</details>")
        lines.append("")

    # Footer
    lines.append("---")
    lines.append(
        "*Generated by [Fenceline](https://github.com/Karmona/Fenceline) "
        "--- supply chain security, community-driven*"
    )

    return "\n".join(lines)
